TARGETS="armeabi-v7a"
#TARGETS="arm64-v8a"
#TARGETS="arm64-v8a armeabi-v7a"
#TARGETS="armeabi-v7a arm64-v8a"
#TARGETS="armeabi-v7a armeabi x86 mips arm64-v8a mips64"
ANDROID_SDK="/Users/sur/Library/Android/sdk"
ANDROID_NDK="/Users/sur/Library/Android/sdk/ndk-bundle"
OPENCV_BUILD_PATH="build"

for TARGET in ${TARGETS}
do    
	mkdir -p ${OPENCV_BUILD_PATH}/${TARGET}
	cd ${OPENCV_BUILD_PATH}/${TARGET}

    cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_shared -DANDROID_ABI=${TARGET} -DANDROID_ARM_NEON=ON -DINSTALL_ANDROID_EXAMPLES=OFF -DANDROID_EXAMPLES_WITH_LIBS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_DOCS=OFF -DWITH_OPENCL=OFF -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake -DENABLE_CXX11=ON -DANDROID_SDK_TARGET=28 -DANDROID_NATIVE_API_LEVEL=28 -DANDROID_SDK=${ANDROID_SDK} -DANDROID_NDK=${ANDROID_NDK} -DBUILD_ANDROID_PROJECTS=OFF ../..
	#cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_ABI=${TARGET} -DANDROID_ARM_NEON=ON -DCPU_BASELINE=SSE2,AVX -DCPU_DISPATCH=SSE4_2,AVX,AVX2 -DINSTALL_ANDROID_EXAMPLES=OFF -DANDROID_EXAMPLES_WITH_LIBS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_DOCS=OFF -DWITH_OPENCL=OFF -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake -DENABLE_CXX11=ON -DANDROID_SDK_TARGET=27 -DANDROID_NATIVE_API_LEVEL=24 -DANDROID_SDK=${ANDROID_SDK} -DANDROID_NDK=${ANDROID_NDK} -DBUILD_ANDROID_PROJECTS=OFF ../..
	cmake --build .

	cd -
done